[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    # Use openzeppelin-contracts v4.7.3 as the some contracts are not compatible with 0.8.15
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "@optimism/=lib/mantle-v2/packages/contracts-bedrock/",
    "@forge-std/=lib/forge-std/src/",
    "@solady/=lib/solady/src",
    # Note: Use zobront/sp1-contracts as the current version for SP1 contracts is not compatible with the hard
    # version for 0.8.15 on some Optimism contracts.
    "@sp1-contracts/=lib/sp1-contracts/contracts/",
    # Optimism repo uses absolute imports, so we need to have remappings for the paths we use.
    "src/libraries/=lib/mantle-v2/packages/contracts-bedrock/src/libraries/",
    "src/L1/=lib/mantle-v2/packages/contracts-bedrock/src/L1/",
    "src/L2/=lib/mantle-v2/packages/contracts-bedrock/src/L2/",
    "src/dispute/=lib/mantle-v2/packages/contracts-bedrock/src/dispute/",
    "@lib-keccak/=lib/lib-keccak/contracts/lib",
    "@rari-capital/solmate=lib/solmate"
]

# Enable read-write access to all files in current directory
fs_permissions = [{ access = "read-write", path = "." }]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
