name: Cost Estimator (10000 blocks) - Sepolia

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: "0 0,12 * * *" # Run the workflow every day at 00:00 and 12:00 UTC

jobs:
  daily-cost-estimator:
    runs-on: [self-hosted, Linux, X64, eks, mantle-default, "sepolia"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cost estimator
        run: |
          source $HOME/.cargo/env
          RUST_LOG=info cargo run --bin cost-estimator --release --features eigenda -- --batch-size 10 --default-range 10 --safe-db-fallback
        env:
          L1_RPC: http://sepolia-archive2.sepolia:8545
          L1_BEACON_RPC: http://sepolia-archive2.sepolia:5052
          L2_RPC: http://mantle-op-geth-rpc3.sepolia:8545
          L2_NODE_RPC: http://mantle-op-node-rpc3.sepolia:8545
          EIGEN_DA_PROXY_URL: http://eigenda-proxy.sepolia:3100
          ROLLUP_CONFIG_PATH: configs/5003/rollup.json

      - name: Upload execution reports
        uses: actions/upload-artifact@v4
        with:
          name: execution-reports
          path: execution-reports/ 