name: Cost Estimator

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: "0 */3 * * *" # Run the workflow every 3 hours at minute 0

jobs:
  daily-cost-estimator:
    runs-on: [self-hosted, Linux, X64, eks, mantle-succinct, "mainnetv2"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cost estimator
        run: |
          source $HOME/.cargo/env
          RUST_LOG=info cargo run --bin cost-estimator --release --features eigenda -- --batch-size 1800 --default-range 1800 --safe-db-fallback
        env:
          L1_RPC: http://ethereum-archive2.mainnet:8545
          L1_BEACON_RPC: http://ethereum-archive2.mainnet:5052
          L2_RPC: http://mantle-op-geth-rpc0.mainnet:8545
          L2_NODE_RPC: http://mantle-op-node-rpc0.mainnet:8545
          EIGEN_DA_PROXY_URL: http://eigenda-proxy.mainnet:3100
          ROLLUP_CONFIG_PATH: configs/5000/rollup.json

      - name: Upload execution reports
        uses: actions/upload-artifact@v4
        with:
          name: execution-reports
          path: execution-reports/ 
